<a href="https://colab.research.google.com/github/Kim-Yeonjoo/DeepLearning/blob/main/2_4_%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%94%94%EC%96%B8%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# 1. scala 값의 기울기 계산
x = tf.Variable(0.)   # 초기값 0

with tf.GradientTape() as tape :  # 연산 과정 기록
  y = 2 * x + 3  # y 계산 위한 규칙

grad_y_x = tape.gradient(y, x)   # y값을 x로 미분
grad_y_x  # 텐서

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [2]:
# 2. 행렬 값의 기울기 계산
x = tf.Variable( tf.zeros((2,2)) )

with tf.GradientTape() as tape :
  y = 2 * x + 3    # 브로드캐스팅 연산 -> y 값은 2행2열

grad_y_x = tape.gradient(y, x)
grad_y_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [9]:
#3. w(선형함수) 값의 기울기 계산
w = tf.Variable(tf.random.uniform((2,2)))   # 가중치 = 기울기
b = tf.Variable(tf.zeros((2,)))   # 벡터로 지정

x = tf.random.uniform((2,2))

with tf.GradientTape() as tape :
  y = tf.matmul(x,w) + b   # 행렬곱(x*w) + 벡터 => 선형함수식

grad_y_w_b = tape.gradient(y, [w,b])  # 편미분
grad_y_w_b   # w의 미분값 / bd의 미분값

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.4658371, 1.4658371],
        [0.649171 , 0.649171 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]

In [6]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.979874  , 0.4339987 ],
       [0.98410785, 0.01295841]], dtype=float32)>

In [4]:
w

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.53470635, 0.51512396],
       [0.38759124, 0.5136676 ]], dtype=float32)>

In [5]:
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
w