<a href="https://colab.research.google.com/github/Kim-Yeonjoo/DeepLearning/blob/main/5_%EC%99%80%EC%9D%B8%ED%92%88%EC%A7%88%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 신경망 생성 - 와인등급 데이터

In [3]:
import pandas as pd

redwine = pd.read_csv('winequality-red.csv', sep=';')
redwine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
from sklearn.model_selection import train_test_split

redwine_X = redwine.iloc[:, :-1].to_numpy()
# 원핫인코딩
redwine_y = pd.get_dummies(redwine.iloc[:, -1]).to_numpy()

# train / test
train_X, test_X, train_y, test_y = train_test_split(redwine_X, redwine_y, test_size = 0.3, random_state=1)
train_X.shape, train_y.shape

((1119, 11), (1119, 6))

# 문제 정의: 와인의 품질속성을 분류하기

1. 모형 설계
 - Sequential()
 - 레이어 1 : 뉴런 50, 활성화함수 relu
 - 레이어 2 : 뉴런 50, 활성화함수 relu
 - 레이어 3 : 뉴런 30, 활성화함수 relu
 - 레이어 4 : 출력 6, 활성화함수 softmax (분류, 확률계산)

2. 속성
 - compile()
 - 최적화: adam
 - 손실함수: categorical_crossentropy
 - 평가지표: accuracy

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

#1. 모델정의
model = Sequential()
model.add(Input(shape=(11,)))  # 입력층 11개 피처 지정
model.add(Dense(50, activation='relu'))   # 은닉층 레이어1
model.add(Dense(50, activation='relu'))   # 레이어2
model.add(Dense(30, activation='relu'))   # 레이어3
model.add(Dense(6, activation='softmax'))  # 출력층 레이어4

model

<Sequential name=sequential, built=True>

In [9]:
#2. 속성 설정 - 컴파일
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [11]:
#3. 모델 훈련
model.fit(train_X, train_y, epochs=200, batch_size=50, verbose=1)

Epoch 1/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5098 - loss: 1.1066 
Epoch 2/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5389 - loss: 1.0110 
Epoch 3/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5490 - loss: 1.0772 
Epoch 4/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5464 - loss: 1.0231 
Epoch 5/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5520 - loss: 1.0224
Epoch 6/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5529 - loss: 1.0532 
Epoch 7/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5867 - loss: 1.0091 
Epoch 8/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5958 - loss: 1.0417 
Epoch 9/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5985 - loss: 0.9660 
Epoch 10/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5828 - loss: 0.9912 
Epoch 11/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5497 - loss: 1.0392 
Epoch 12/200
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step -

In [13]:
#4. 평가
pred = model.predict(test_X)
pred

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[1.97454239e-04, 3.57216806e-03, 8.30383658e-01, 1.55714154e-01,
        1.00800386e-02, 5.26210060e-05],
       [3.75228206e-04, 2.21769772e-02, 7.93335736e-01, 1.83934450e-01,
        1.55356174e-04, 2.22632425e-05],
       [5.17724511e-05, 3.63617740e-03, 4.27400887e-01, 4.07529205e-01,
        1.16839893e-01, 4.45420519e-02],
       ...,
       [1.27272857e-02, 1.13816030e-01, 6.74305558e-01, 1.98043332e-01,
        4.99116315e-04, 6.08754752e-04],
       [2.55419782e-05, 1.30809415e-02, 5.45528352e-01, 4.17066395e-01,
        2.41018701e-02, 1.96912952e-04],
       [3.42905085e-04, 1.81954168e-02, 3.01890731e-01, 5.72150648e-01,
        3.52224223e-02, 7.21979886e-02]], dtype=float32)

In [15]:
#4-1. 제일 높은 평가 출력
import numpy as np
pred_ag = np.argmax(model.predict(test_X), axis=1)
pred_ag

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([2, 2, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 2, 4, 2, 2, 3, 2, 2, 2, 2, 2,
       2, 3, 2, 3, 3, 2, 2, 4, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 3, 2, 2, 3,
       2, 2, 2, 2, 2, 3, 2, 1, 3, 2, 2, 3, 3, 3, 3, 2, 3, 2, 2, 2, 2, 2,
       3, 2, 2, 3, 2, 3, 2, 3, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3,
       2, 3, 2, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       3, 2, 3, 2, 2, 4, 2, 2, 2, 2, 2, 4, 3, 2, 2, 2, 2, 2, 4, 3, 2, 2,
       3, 2, 2, 3, 2, 4, 2, 2, 2, 2, 2, 2, 3, 4, 2, 2, 2, 3, 2, 3, 2, 2,
       3, 3, 3, 3, 3, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 2, 4, 3, 2, 2, 3, 3, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 3, 3, 2, 2, 4, 3, 2, 2, 3, 3, 2, 2, 3, 2, 2, 2, 3, 3,
       3, 2, 2, 4, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 3, 2,
       2, 2, 3, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 4, 2, 3, 2, 2, 2,
       3, 2, 2, 2, 2, 3, 3, 2, 3, 3, 2, 3, 2, 2, 2,

In [16]:
#5. 실제값과 비교
np.argmax(test_y, axis=1)

array([2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 2, 3, 2, 2, 2, 3, 3,
       2, 3, 3, 3, 3, 3, 3, 4, 3, 3, 2, 3, 2, 3, 2, 4, 3, 2, 3, 2, 2, 3,
       2, 3, 2, 2, 2, 3, 2, 1, 4, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 3, 2, 3,
       4, 3, 3, 3, 2, 3, 3, 3, 2, 2, 3, 3, 2, 3, 2, 2, 2, 3, 2, 2, 2, 4,
       2, 3, 2, 4, 2, 3, 2, 2, 3, 2, 0, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 3, 2, 4, 2, 2, 2, 2, 1, 4, 4, 2, 2, 2, 3, 2, 4, 4, 3, 2,
       4, 2, 3, 4, 2, 4, 3, 3, 2, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3,
       2, 4, 2, 3, 3, 3, 5, 3, 2, 2, 3, 3, 1, 2, 2, 3, 3, 3, 1, 4, 2, 3,
       2, 2, 2, 2, 3, 3, 2, 3, 3, 3, 4, 3, 1, 3, 2, 3, 3, 2, 3, 2, 1, 2,
       3, 2, 4, 2, 4, 2, 4, 3, 2, 2, 3, 2, 2, 4, 2, 3, 2, 3, 2, 2, 4, 3,
       2, 3, 2, 2, 3, 2, 1, 4, 4, 4, 3, 3, 4, 3, 3, 3, 3, 3, 2, 1, 3, 2,
       4, 3, 3, 5, 3, 2, 2, 2, 2, 1, 3, 3, 3, 2, 2, 1, 2, 2, 3, 2, 2, 2,
       1, 3, 2, 2, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 2, 2, 3, 1, 1, 2, 3, 2,
       3, 2, 2, 2, 3, 3, 3, 2, 3, 4, 2, 2, 2, 2, 3,

In [17]:
pd.crosstab(np.argmax(test_y, axis=1), pred_ag, margins=True)

col_0  0  1    2    3   4  All
row_0                         
0      0  0    1    1   0    2
1      1  1   16    2   1   21
2      0  3  179   24   1  207
3      0  0  111   78   6  195
4      0  0    8   31  13   52
5      0  0    1    0   2    3
All    1  4  316  136  23  480

In [18]:
#6. 수치로 확인하기
loss, accuracy = model.evaluate(test_X, test_y)
print('loss : ', loss)
print('accuracy : ', accuracy)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5824 - loss: 1.0714  
loss :  1.1023300886154175
accuracy :  0.5645833611488342


### 훈련 시점
accuracy: 0.6577 - loss: 0.8025  
=> 실제 정확도가 훈련 시점보다 떨어짐.

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 50)                  │             600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 50)                  │           2,550 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 30)                  │           1,530 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 6)                   │             186 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14,600 (57.04 KB)

 Trainable params: 4,866 (19.01 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 9,734 (38.03 KB)

# 정확도 올리기
1. 모형 구조 변경
2. 최적화 함수 바꾸기
3. 에포크 횟수 늘리기

In [20]:
# 모형 구조 재설정
model_1 = Sequential()
model_1.add(Input(shape=(11,)))  # 입력층 11개 피처 지정
model_1.add(Dense(128, activation='relu'))   # 은닉층 레이어1
model_1.add(Dense(128, activation='relu'))   # 레이어2
model_1.add(Dense(64, activation='relu'))   # 레이어3
model_1.add(Dense(6, activation='softmax'))  # 출력층 레이어4

model_1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# epochs 횟수 늘리기
model_1.fit(train_X, train_y, epochs=500, batch_size=50, verbose=1)

Epoch 1/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4537 - loss: 1.4957
Epoch 2/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4912 - loss: 1.1432 
Epoch 3/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4941 - loss: 1.1358
Epoch 4/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5074 - loss: 1.1694 
Epoch 5/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5173 - loss: 1.2126
Epoch 6/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5031 - loss: 1.1486
Epoch 7/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5344 - loss: 1.1530 
Epoch 8/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5142 - loss: 1.0961 
Epoch 9/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5290 - loss: 1.1013 
Epoch 10/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5159 - loss: 1.0766
Epoch 11/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5498 - loss: 1.0622
Epoch 12/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accu

In [21]:
loss, accuracy = model_1.evaluate(test_X, test_y)
print('loss : ', loss)
print('accuracy : ', accuracy)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6109 - loss: 3.0591
loss :  3.23287296295166
accuracy :  0.6000000238418579


In [27]:
model_2 = Sequential()
model_2.add(Input(shape=(11,)))  # 입력층 11개 피처 지정
model_2.add(Dense(164, activation='relu'))   # 은닉층 레이어1
model_2.add(Dense(164, activation='relu'))   # 레이어2
model_2.add(Dense(128, activation='relu'))   # 레이어3
model_2.add(Dense(6, activation='softmax'))  # 출력층 레이어4

model_2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# epochs 횟수 늘리기
model_2.fit(train_X, train_y, epochs=300, batch_size=50, verbose=1)

Epoch 1/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.3724 - loss: 2.5208
Epoch 2/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4687 - loss: 1.2515
Epoch 3/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4975 - loss: 1.1900
Epoch 4/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5180 - loss: 1.1226
Epoch 5/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4957 - loss: 1.1700
Epoch 6/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5238 - loss: 1.0796
Epoch 7/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5000 - loss: 1.1574
Epoch 8/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4939 - loss: 1.1508
Epoch 9/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5297 - loss: 1.1200
Epoch 10/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5257 - loss: 1.0903
Epoch 11/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5326 - loss: 1.0852
Epoch 12/300
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accurac

In [28]:
loss, accuracy = model_2.evaluate(test_X, test_y)
print('loss : ', loss)
print('accuracy : ', accuracy)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6123 - loss: 2.0197  
loss :  2.076239585876465
accuracy :  0.5958333611488342
